version: '3.8'

services:
  ultimate-ai-bot:
    build: .
    container_name: ultimate-ai-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge